input EventInput {
  eventName: String!
  date: String!
  totalAmount: Float!
  status: String!
  GroupId:ID!
}

type User {
  id: ID!
  username: String!
  email: String!
  password: String!
  balance: Float
  events: [Event!]!
}

type Group {
  id: ID!
  groupName:String!
  users: [User!]!
  admin: User
}

type Event {
  id: ID!
  eventName: String!
  date: String!
  totalAmount: Float!
  paidByUser: [User]!
  status: String!
}

type UserJoined{
  id:ID!,
  username:String
}

enum EventStatus {
  OPEN
  CLOSE
}

type Query {
  getUsers: [User]
  getUserById(username:String!): User!
  getParticipatedEvents(id: ID!): [Event!]
}

input createUserInput {
  username: String!
  email: String!
  password: String!
  events: EventInput
}

input createGrpInput {
  users: [ID!]!
  groupName:String!
  admin: ID!
}

input userEventInput {
  userId:ID!
  username:String!
  eventName:String!
  eventId:ID!
}

input UserInput {
  id: ID!
  username:String!
  groupId: ID!
}

input paymentInput {
  user: UserInput!
  amount: Float!
  event: EventInput
}

type Mutation {
  createUser(userDetails: createUserInput!): User!
  createGroup(groupDetails: createGrpInput): Group!
  postEvent(event: EventInput): Event!
  joinEvent(userEventInput: userEventInput): Event
  joinGroup(user: UserInput!): Group
  onPayment(payment: paymentInput): User
}

type Subscription{
  GroupCreated(id:ID!):Group
  EventCreated(groupId:ID!):Event
  CheckNewGroupUsers(groupId:ID!):UserJoined
  CheckNewEventpUsers(eventId:ID!):UserJoined
}